apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcast
  template:
    metadata:
      labels:
        app: broadcast
    spec:
      containers:
        - name: broadcast
          image: BROADCAST/IMAGE
          imagePullPolicy: Always
          env:
            - name: TODO_CREATED_SUBJECT
              value: "todo_created"
            - name: TODO_COMPLETED_SUBJECT
              value: "todo_completed"