apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
spec:
  template:
    spec:
      containers:
        - name: broadcast
          env:
            - name: DISCORD_WEBHOOK_URL
              value: "https://discord.com/api/webhooks/{generated part of the url}"
            - name: NATS_HOST
              value: "nats://my-nats-prod:4222"