apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Wilky2/KubernetesSubmissions
    path: todo-app/config/overlays/prod
    targetRevision: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: <strong>true</strong>
      selfHeal: <strong>true</strong>