apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Wilky2/KubernetesSubmissions
    path: todo-app/config/overlays/staging
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: <strong>true</strong>
      selfHeal: <strong>true</strong>