spring.application.name: log-output-app

server.port: ${PORT:8080}

file:
  path: ${FILEPATH:/usr/src/app/files}
  name: 'app-log.json'
  pingpong: 'pingpong.txt'

pingpong:
  url: ${PINGPONG_URL}

greeting:
  url: ${GREETING_URL}

message: ${MESSAGE}