apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-cron
spec:
  schedule: "0 2 * * *"  # every day at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgres-backup
              image: postgres:18rc1-alpine3.22
              env:
                - name: PGHOST
                  value: "postgres-project-svc"
                - name: PGUSER
                  value: "postgres"
                - name: PGPASSWORD
                  value: "postgres"
                - name: PGDATABASE
                  value: "todo_db"
              command:
                - /bin/sh
                - -c
                - |
                  BACKUP_DIR=/backup
                  mkdir -p $BACKUP_DIR
                  TIMESTAMP=$(date +%Y%m%d%H%M)
                  echo "Creating backup todo_db_$TIMESTAMP.sql"
                  pg_dump -U $PGUSER -h $PGHOST $PGDATABASE > $BACKUP_DIR/todo_db_$TIMESTAMP.sql
                  echo "Backup complete"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-backup-pvc