apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-dep
spec:
  template:
    spec:
      containers:
        - name: broadcast
          env:
            - name: DISCORD_WEBHOOK_URL
              value: ""
            - name: NATS_HOST
              value: "nats://my-nats:4222"