apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend-dep
spec:
  template:
    spec:
      containers:
        - name: todobackend
          env:
            - name: NATS_HOST
              value: "nats://my-nats-prod:4222"