apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-cron
spec:
  schedule: "0 * * * *"   # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wikipedia-todo-generator
              image: curlimages/curl:8.10.1
              command:
                - /bin/sh
                - -c
                - |
                  echo "Fetching random Wikipedia article..."
                  URL=$(curl -s -o /dev/null -w "%{redirect_url}" https://en.wikipedia.org/wiki/Special:Random)
                  echo "Got random article: $URL"
                  echo "Posting todo to backend..."
                  curl -X POST http://todobackend-svc:4345/todos \
                       -d "name=Read $URL"
          restartPolicy: OnFailure
