apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim-prod # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: my-pv-prod # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi