on:
  release:
    types: [published]

jobs:
  update-prod-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git tag -f prod $GITHUB_REF_NAME
          git push origin prod -f
